language: php

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  include:
    - env: TEST_RELAXED=Drupal
      php: 5.4
      SCRIPT=$TRAVIS_BUILD_DIR/../drupal/tests/scripts/drupal.sh
    - env: TEST_RELAXED=Drupal
      php: 5.5
      SCRIPT=$TRAVIS_BUILD_DIR/../drupal/tests/scripts/drupal.sh
    - env: TEST_RELAXED=CouchDB
      php: 5.4
      services: couchdb
      SCRIPT=$TRAVIS_BUILD_DIR/../drupal/tests/scripts/couchdb.sh
    - env: TEST_RELAXED=CouchDB
      php: 5.5
      services: couchdb
      SCRIPT=$TRAVIS_BUILD_DIR/../drupal/tests/scripts/couchdb.sh

before_install:
  # Update Composer so that the Drush installation doesn't fail.
  - composer selfupdate

install:
  # Install Apache.
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Set up PHP-FPM.
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Set up the Apache vhost.
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Install Drush.
  - export PATH=$PATH:/home/travis/.composer/vendor/bin
  - composer global require drush/drush:7.0.0-alpha5

before_script:
  # Checkout a directory structure with all dependencies.
  - git clone --depth 1 --branch 2335879-2342543-1869548 https://github.com/dickolsson/drupal-core.git $TRAVIS_BUILD_DIR/../drupal
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-key_value.git $TRAVIS_BUILD_DIR/../drupal/modules/key_value
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-multiversion.git $TRAVIS_BUILD_DIR/../drupal/modules/multiversion
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/relaxed

  # Install the site that will host our tests.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --db-url=mysql://root:@127.0.0.1/drupal minimal

  # Enable required modules and ignore any output to not break the test.
  - drush --yes pm-enable key_value, multiversion, relaxed || true

script:
  # Enable Simpletest.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - drush en --yes simpletest
  - drush cr
  - bash $SCRIPT


